NishantRana07/HrRoadways

src/App.jsx
src/components/Aboutus.jsx
src/components/footer.jsx

Footer Component Highlights:
Responsive Design: Adapts seamlessly to various screen sizes using flexible layouts.
Company Info: Links to "About Us," services, privacy policy, and affiliate program.
Support Section: Includes quick access to FAQs, shipping, returns, and payment options.
Social Media Integration: Features stylish, interactive icons for Facebook, Twitter, Instagram, and LinkedIn.
Custom Styling: Inline CSS ensures consistent and modern design aesthetics.
This footer enhances navigation, user engagement, and overall site professionalism.
completed the footer addition review it please

footer is added

---

src/components/footer.jsx

Updated the Twitter icon to the new "X" logo to align with Twitter's rebranding. This change ensures the footer reflects the current branding and avoids any outdated representation.

Updated Twitter icon

---

index.html

I have put LogoHR.png
Pls tell if you require Logo.png was to be put

Updated Favicon icon and title

---

index.html
script.js
style.css

**fixed issue no: #35**
🏠 **Enhanced Navigation on the Homepage with a Scroll-to-Top Button**  
I have successfully added a **scroll-to-top button** on the homepage, making it easier for users to navigate back to the top of the page with just one click.  
✨ Key Features of the Scroll Button:  
1️⃣ **Smooth Scrolling:** Implemented a seamless scrolling effect for a better user experience.  
2️⃣ **Responsive Design:** Ensured the button adapts to all devices, including desktops, tablets, and mobile screens.  
3️⃣ **Hover Effects:** Added an interactive hover effect using Font Awesome for a visually appealing and modern design.  
4️⃣ **Dynamic Visibility:** The button appears only after users scroll down a certain distance, keeping the interface clean.  
5️⃣ **Improved Usability:** Provides …

⬆️ Adding a Scroll-to-Top Button to the Homepage

---

src/App.jsx
src/assets/Blog.css
src/components/Blog.jsx

Related to #3
Add a new Blog section to the application.
* **Blog Component**: Create a new `Blog` component in `src/components/Blog.jsx` to display blog posts. Add state management for blog posts, a form to create new blog posts, and a list to display existing blog posts.
* **Styling**: Add a new CSS file `src/assets/Blog.css` for styling the Blog component, including styles for the form and the list of blog posts.
* **Routing**: Modify `src/App.jsx` to import the `Blog` component and add a new route for the Blog section.
* **Navigation**: Update `index.html` to include a link to the Blog section in the navigation menu.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/NishantRana07/HrRoadways/pull/39?shareId=c2c0e25b-5e47-4b1f-b1f0-ea7095 …

Add blog section

---

Database/YourCity/BusData.json

Fixes #8
Add new bus routes data for a city in the `Database` directory.
* Create a new folder named `YourCity` in the `Database` directory.
* Add a new JSON file named `BusData.json` in the `YourCity` folder.
* Include bus routes, departure times, distances, prices, bus types, and contact information in the specified format.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/NishantRana07/HrRoadways/pull/42?shareId=bb39969f-7d54-48e4-ba3d-a45509c88818).

Add your city bus routes

---

index.html
package.json
postcss.config.js
src/App.jsx
src/assets/nav.css
src/components/footer.jsx
src/components/hero.jsx
src/components/nav.jsx
src/index.css
src/main.jsx
tailwind.config.js
vite.config.js

Made changes to rectify issue #28

Homepage Functionalities added 

---

src/components/nav.jsx

Changes made to cater issue #45

Navigation Bar updated

---

src/assets/nav.css
src/components/nav.jsx

Fixes #47
Fix the Hindi to English button functionality in the `Navigation` component.
* **Add props to `Navigation` component:**
- Add `isHindi` and `onToggleLanguage` props to `Navigation` component.
- Use `isHindi` prop to determine the current language and update UI accordingly.
- Update language toggle button to call `onToggleLanguage` function.
* **Update translations:**
- Add translations for both English and Hindi languages.
- Use `currentLanguage` variable to store the current language based on `isHindi` state.
* **Handle scroll event:**
- Add `useEffect` to handle scroll event and set `isScrolled` state.
* **Update services dropdown:**
- Use `currentLanguage` variable to set the titles of services dropdown items.
---
For more details, open the [Copilot Workspace …

Fix Hindi-English button functionality

---

package-lock.json
src/App.jsx
src/assets/Blog.css
src/assets/DonatePage.css
src/components/Blog.jsx
src/components/DonatePage.jsx
src/components/nav.jsx

**Description:**
Achieved all features told in issue #62 .
Closes #62 
And one request can i get hard tag as i created one page and edited ui of blog page with so many line insertion.
<hr/>
**Preview:**
**Donate Page:** 
**Improved Blog:** 
**From:** 
**To:**

Added Donate page and blog page UI Improv

---

src/App.jsx
src/components/HelpLinepage.jsx
src/components/nav.jsx

Helpline Page using Tailwind CSS, ensuring a clean, responsive layout with a color palette matching the homepage. Key features include:
Hover Effect: FAQs highlight with a light blue background when hovered.
Tailwind Utilities: Simplified styling with classes for spacing, colors, and shadows.
Responsive Design: Optimized layout for all screen sizes.
This approach improves usability and ensures consistency across the site.

updated the helpline page 

---

libs/utils.js
src/App.jsx
src/assets/Trip.css
src/components/HelpLinepage.jsx
src/components/Trip.jsx
src/index.css

Changes made to resolve issue #77

contact page updated

---

src/components/Blog.jsx

Changes made to resolve issue #75

Blog page UI enhanced and few functionalities added

---

src/assets/DonatePage.css
src/components/DonatePage.jsx

**fixed issue #73**
🔹 **What’s New?**  
I have updated the input fields in the donation form by adding **placeholders** to guide users on what to enter. Along with this, I introduced **hover and focus effects** to make the input fields more interactive and visually appealing.  
🔹 **Improvements**:  
- Added **clear and meaningful placeholders** for all input fields to enhance user guidance.  
- Implemented **hover effects** that highlight the input fields with a light blue background for better engagement.  
- Designed a **focus effect** with a glowing border to draw attention to the active input field.  
🔹 **Why It Matters?**  
These changes improve the **user experience** by making the form more intuitive and engaging, ensuring users feel confident while entering their details. …

🎨✨ Enhanced Input Fields with Placeholders and Interactive Effects 🖱️💡

---

src/components/TravelLocation.jsx

@NishantRana07 Changes made to resolve issue #82

travelpage updated

---

src/App.jsx
src/components/faq.jsx
src/components/footer.jsx

Added faq page to make user friendly.

Added faq page

---

src/components/DonatePage.jsx

@NishantRana07 Changes made to resolve issue #83

Features added in the Donations Page

---

src/components/Aboutus.jsx

@NishantRana07 Made Changes to rectify issue #81

aboutus page made more dynamic and updated

---

package-lock.json

Error
404: NOT_FOUND
Code: NOT_FOUND
ID: bom1::25kl5-1737561997812-70d7a1d6d44

Trying to fix files not loading

---

package-lock.json
src/App.jsx
src/assets/AffiliateProgram.css
src/components/AffiliateProgram.jsx
src/components/footer.jsx

- Affiliate page made (jsx + css)
- page is responsive
- all navigation onclicks updated

#97 Affiliate Program Page applied

---

src/components/SearchWindow.jsx
src/components/nav.jsx

Changes made to rectify issue #108 
this redirects to the schedule page

Search routes button updated

---

src/components/TrafficUpdates.jsx
src/components/hero.jsx

Changes made to resolve issue #118

Traffic and other alert added on homepage

---

src/components/footer.jsx

Changes made to resolve issue #119

footer updated

---

src/App.jsx
src/assets/ContactUs.css
src/components/ContactUs.jsx
src/components/footer.jsx

- Files add ContactUs.jsx and .css
- page is responsive
- package lock also updated
- app.jsx and footer linked
- i will add hindi translation in my hindi pr #120

#124 Contact Us page Created

---

src/assets/footer.css
src/assets/hero.css
src/components/footer.jsx
src/components/hero.jsx

Apart from the issues mentioned in #123, I have also fixed the layout of the new footer
- Homepage Overlap fixed
- Code is readable in Hero.jsx
- all css moved out of Hero.jsx to hero.css
- Homepage Arrangement Fixed
- Code is readable again in footer.jsx
- footer.css updated
- double lindkln icon changed in footer to share icon

#123 Home, Footer Layout and code readability fixed

---

src/components/AffiliateProgram.jsx

Changes made to resolve issue #136

affilate program page updated

---

package-lock.json
src/components/DonatePage.jsx

**fixed issue no: #139**
---
- Added a **placeholder text** in the donation input field for better user guidance. 📝  
- Helps users understand what the input field is meant for and reduces confusion.
- Enhances **user experience (UX)** by providing clear instructions in the donation field.  
- Ensures **usability improvements** for first-time users visiting the donate page.  
- **Clarity**: Users can easily understand the input requirements without needing external instructions.  
- **Improved Accessibility**: Placeholder text serves as a visual aid for users.  
- **Seamless Flow**: Users are guided intuitively to complete their donation.  
---
---
- Verified that the placeholder text is visible on all browsers. ✅  
- Checked responsiveness to ensure the placeholder is displayed correctly …

🚀 Add Placeholder for Donation Section 💳

---

src/assets/nav.css
src/components/nav.jsx

Improves the Navbar Functionality 
Fixes #106 
Checklist:

nav is updated 

---

src/assets/nav.css
src/components/nav.jsx

Reverts NishantRana07/HrRoadways#150

Revert "nav is updated "

---

src/App.jsx
src/assets/luxury.css
src/components/RoyalHaryanaTourism.jsx
src/components/footer.jsx

Changes made to resolve issue #132

luxury destination page added

---

src/components/InfoPage.jsx
src/components/policy.jsx

Changes made to resolve issue #133

policy page updated and features added

---

script.js
style.css

1. Button Appearance
Background Color:
First code: background-color: #007BFF (blue).
Second code: background-color: #e74c3c (warm red) and includes a different color for dark mode (#ff6b6b).
Button Size:
First code: width: 50px; height: 50px.
Second code: width: 60px; height: 60px (slightly larger).
Font Size:
First code: font-size: 20px.
Second code: font-size: 24px (larger icon).
Box Shadow:
First code: box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2) (simpler).
Second code: box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3) (more pronounced shadow) and dark theme shadow (rgba(255, 255, 255, 0.1)).
Z-Index:
First code: No z-index specified.
Second code: z-index: 1000 to ensure it stays on top.
2. Dark Theme Styling
First Code:
No dark theme-specific styles.
Second Code:
Adds dark theme styles using …

To add some features and fixing the bugs

---

src/App.jsx
src/assets/OurServices.css
src/components/Services.jsx
src/components/footer.jsx

changes made to resolve issue #137

Our Services Page created 

---

package-lock.json
src/App.jsx
src/components/Blog.jsx
src/components/HelpLinepage.jsx
src/components/TravelLocation.jsx
src/components/faq.jsx

Translation logic applied on these pages
- 24*7 Helpline
- Faq
- blog
- visit cities
isHindi function update in app.jsx

#120 Completed Translation updated

---

src/App.jsx
src/components/ContactUs.jsx
src/components/DonatePage.jsx
src/components/InfoPage.jsx
src/components/Paymentoptions.jsx
src/components/RoyalHaryanaTourism.jsx
src/components/Services.jsx
src/components/Track.jsx

#158 Completed
- pages coverted are:
- Privacy Policy
- Our services
- Contact us
- Bus status
- Luxury destination
- Payment
- Donate Page

All pages are in Hindi now

---

src/components/TravelLocation.jsx

**fixed issue no: #166**
🌟 I’ve introduced a **hovering effect** to the search box on the **Travel Page** to enhance its **visual appeal** and improve the **user experience**.  
💡 **Key Details of the Update:**  
1️⃣ **Dynamic Hover Effect:**  
- When users hover over the search box, the **border color changes to blue** 🟦, and a **subtle shadow** appears around the box, giving it a modern and interactive look.  
2️⃣ **Pointer Cursor Added:**  
- The cursor changes to a **pointer hand icon**, clearly indicating the search box is clickable.  
3️⃣ **Smooth Transition:**  
- A **300ms transition** makes the hover effect smooth and visually pleasing, creating a polished experience.  
🎯 **Why This Matters:**  
- The hover effect not only improves the aesthetics but also provides feedback to …

✨ Added Hovering Effect to the Search Box on Travel Page! 🧳

---

src/styles/nav.css

Made the required changes in nav.css. 
Also tested the result. Kindly verify once as well.

Fixed NavBar Drop Down Issue

---

src/styles/hero.css

**fixed issue no: #182**
We’ve made the **"Search Buses"** section on the homepage more interactive and user-friendly! 🎉 Now, when users hover over the input field, they’ll experience a **smooth and visually appealing effect**, making the UI more engaging.  
✅ **Border Highlighting:** The border color dynamically changes on hover for better visibility.  
✅ **Background Animation:** A subtle background color transition enhances the user experience.  
✅ **Glow Effect:** The input field now has a soft glow, making it stand out.  
✅ **Scale Effect:** Slight enlargement (`scale(1.02)`) to improve focus.  
✅ **Placeholder Animation:** The placeholder text changes color and weight, making it more intuitive.  
These changes make the **"Search Buses"** section not just functional but also visually …

🚀 Added Hovering Effect in the "Search Buses" Section on the Homepage 🚌

---

src/components/BusDetailModal.jsx
src/components/hero.jsx
src/styles/hero.css
src/styles/modal.css

- Modal Created
- Hero prepared for booking page
- new functions set up for informatn transfer
@NishantRana07 Please accept this pr

#141 Complete

---

src/App.jsx
src/components/BestRides.jsx

Changes made to resolve issue #165

Best Rides Page Created

---

.gitignore
package-lock.json
package.json
src/components/WeatherUpdates.jsx
src/components/hero.jsx

- Realtime Weather Now in the Site!!!
- OpenWeather API implemented
- Alll checks completed
- popular routes weather added
@NishantRana07 Please Approve this PR

#181 Completed

---

src/components/footer.jsx
src/styles/footer.css

Reverts NishantRana07/HrRoadways#209

Revert "Footer Redesigned"

---

src/App.jsx
src/components/Tutorial.jsx
src/components/TutorialStep.jsx
src/components/nav.jsx
src/styles/nav.css

- Base Tutorial Page Created
- Responsive Page
- Collapsable box with animation
- Added youtube embedded player for future screen recording tutorial
- Screensots and more data to be added once booking page is complete
https://github.com/user-attachments/assets/f184a80f-9728-4cea-9414-eed4fe263265

#162 Completed tutorial page created

---

src/components/hero.jsx

- Chandigarh no longer appears 3 times
- Gurugram redundancy removed
- zirakpur redundancy removed
- empty price removed

#217 Completed Json updated to remove redundant data

---

src/components/HelpLinepage.jsx

- Search Bar alignment done and bug removed
- place holder now clearly visible
@NishantRana07 Please Check and Approve this PR

#218 Completed

---

TranslationLink.md
src/components/Aboutus.jsx
src/components/Blog.jsx
src/components/DonatePage.jsx
src/components/TravelLocation.jsx
src/components/Trip.jsx
src/components/hero.jsx

- Translations Readme.md added for jsonblob links
**Pages Updated Are** :
1. Hero.jsx
2. Trip.jsx
3. Travellocations.js
4. Aboutus.jsx
5. Blog.jsx
6. DonatePage.jsx

#216 CompletedTranslations of 6 pages hosted

---

src/App.jsx
src/components/Timetable.jsx
src/components/Trip.jsx

Changes made to resolve issue #235

Timetable page added

---

src/App.jsx
src/components/Rules.jsx
src/components/nav.jsx

Changes made to rectify issue #234

Rules page added

---

src/components/hero.jsx
src/styles/hero.css

- Comments added for readability
- Suggestions Container replaced with dropdown (keyboard functionality maintained and outside click added)
- Components made reusable
- line of code reduced by 200 lines in hero.jsx
- Redundant and unused styles removed in hero.css
@NishantRana07 Please approve this PR
- Hero.jsx is now ready for dark mode and booking page

#228 Completed hero.jsx restructured

---

libs/languageStorage.js
package-lock.json
src/App.jsx
src/components/nav.jsx

Fixed issue #263
Add User Language Preference Storage and Persistence
Changes:
Added libs/languageStorage.js utility for localStorage management
Updated App.jsx to initialize and persist language state
Language preference now survives page refreshes and browser sessions
Why:
Improves user experience by remembering language choice
Follows standard web app persistence practices
Fixes Level 2 priority bug
Testing:
Toggle works, persists on refresh and maintains across sessions

Fixed User Language Preference Storage and Persistence Issue

---

src/assets/translations.json
src/components/TravelLocation.jsx

**Description:**
This PR resolves three key issues:
1.  **Technology Stack Images:** Fixed missing technology logos on the "About Us" page by correctly placing images in `public/tech_logos` and updating component references.
2.  **Travel Locations Page (Blank Screen):** Corrected the blank page issue on the `/travellocations` route. This was due to a failed external API call; the data fetch has been replaced with local JSON data (`src/assets/translations.json`), and the component updated accordingly.
3.  **Specific Travel Location Images:** Resolved missing images for the newly added Panipat and Yamunanagar travel locations by hosting their images locally in `public/travel_locations` and updating the image paths in `src/assets/translations.json`.
**ScreenShort**

Fix: Display issues for Technology Stack images & Travel Locations page and Added Filer 

---

src/components/nav.jsx

Reverts NishantRana07/HrRoadways#324

Revert "fix(nav): stabilize “Services” dropdown hover with 200ms delay"

---

src/components/nav.jsx

What I Did:
- Improved the visual clarity of the language toggle component.
- Applied conditional styling to highlight the selected language (EN or HI).
- Added spacing and smoother transitions for a cleaner UI feel.
Why:
This makes the language toggle more intuitive for users by clearly indicating the selected option.
---
Tested on local setup and verified working. ✨

Improved language toggle switch UI for better clarity

---

src/components/footer.jsx

This Pull request address to the issue number 297 --
(Updated the social media links in the footer to ensure they redirect to the correct platforms. This change improves the site's professionalism and user experience by allowing visitors to connect directly through verified social channels. All links have been tested for accuracy and responsiveness to maintain consistency across devices.
Please review it and let me know any further changes required @NishantRana07 !!))

Issue #297 Resolved > Fixed Footer Social Links!

---

src/components/Blog.jsx

Fixed the problem of the blog page issue of going blank after certain time.
Closes #337 
https://github.com/user-attachments/assets/f884b9f6-b889-485f-9c01-969e9d2695ca

Fix: Blog page fixed

---

src/styles/luxury.css

Refactored the RoyalHaryanaTourism component stylesheet to ensure responsiveness across mobile and tablet devices. Adjusted layout, image scaling, and typography for improved user experience and visual consistency with project design.
Closes #299 
https://github.com/user-attachments/assets/2a584f91-b09e-45c8-9761-2ed704631626

Make /luxury Route Responsive for Mobile & Tablet Users

---

src/components/Blog.jsx
src/components/fallbackData.jsx

This PR integrates sample (hardcoded) translation data directly into the Blog page as a temporary fallback. It removes the dependency on the external translationsUrl, which is currently invalid or missing.
Closes #344
1.  Removed usage of translationsUrl due to invalid blob.
2. Introduced fallbackData.jsx file to temporarily store sample translation and post data.
3. Modified the Blog component to use fallbackData instead of fetching from remote.
4.  Ensured both Hindi and English language support work seamlessly with sample data.
- My code follows the style guidelines of this project
-  I have performed a self-review of my code
-  I have commented my code where necessary
- My changes generate no new warnings or errors

Sampledata in blog page

---

src/components/nav.jsx
src/styles/nav.css

---
This PR enhances the navigation bar by highlighting the active navigation link. It uses React Router's `<NavLink>` and a new CSS rule for the `.active` class, improving user experience by clearly indicating the current page.
Closes #311
before:
https://github.com/user-attachments/assets/ee6d37c5-6d20-4127-92a0-c75a5ab5de9a
after:
https://github.com/user-attachments/assets/a9be180a-df24-4f08-908d-2cb4382b2a21
---

feat: highlight active navigation link using NavLink and CSS

---

src/components/Track.jsx

Now User can see the Track page with good Font Color 
Closes #356

Font Colors are now visible in trackPage

---

ROUTES_GUIDE.md

This PR adds new functionality/fixes/improvements to the project.  
**Summary:**  
- Added new bus route entries in `public/Places/HARYANA.json`  
- Ensured JSON format and data consistency  
- Updated contribution guide where applicable  
---
Closes #314 
---
- ✅ Manual validation of updated JSON using linter  
- ✅ Entries verified for correct format and field values  
---
---

Added Create ROUTES_GUIDE.md

---

src/components/hero.jsx
src/styles/hero.css

Reverts NishantRana07/HrRoadways#375

Revert "Added Typewriter Effect to the Main Heading!"

---

src/App.jsx
src/components/ScrollButton.jsx

Add scroll to top button

---

package.json
src/App.jsx
src/components/ForgotPassword.jsx
src/components/Login.jsx
src/components/ProtectedRoute.jsx
src/components/Register.jsx
src/components/Register.tsx
src/components/Userprofile.jsx
src/components/nav.jsx
src/i18n/locales/en.json
src/i18n/locales/hi.json
src/store/store.js

Closes #384 
- [ *] Other evidence (logs/screenshots/etc)
- [ *] Code review
- [ *] My code follows the style guidelines of this project
- [* ] I have performed a self-review of my code
- [ *] I have commented my code where necessary

Auth frontend

---

src/assets/translations.json
src/components/TravelLocation.jsx

Updated the Broken images in /travellocations route to:
Replaced the expired web URLs with ones hosted on i.ibb.co.
Closes #390

Fix:Updated broken image links with new ones in travellocations route

---

src/App.jsx

contribution-template

---

src/components/Services.jsx
src/styles/OurServices.css

Now user can read the text in our services page. Also created gap between Stats Section and Additional Information Section. 
Link: https://github.com/NishantRana07/HrRoadways/issues/438
Closes #438 
https://github.com/user-attachments/assets/7dff85ab-0433-4d52-b0d1-2a5982d1c147
- [ x] Manual testing steps
- [ x] Other evidence (logs/screenshots/etc)
- [ x] Code review
- [ x] Final test cases
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings or errors
@Bucke200  Hey Check this out and merge this PR. 
Thank You!

Solved Text Readability Issue in Our Services Page

---

src/components/ScrollButton.jsx

- Resolved issue where the scroll-to-top button overlapped with other UI elements.
- Updated the button's border radius to enhance visual consistency.
- Prevents UI interference caused by the scroll button.
- Ensures a smoother and more modern UI experience.
---
Feel free to review and suggest any improvements!

Fixed ScrollBtn overlap and there Radius

---

package-lock.json
package.json
src/App.jsx
src/components/Login.jsx
src/components/SignUp.jsx
src/components/ToastTest.jsx
src/components/Userprofile.jsx
src/components/nav.jsx

This PR adds a Toast notification in the **UserProfile** component to confirm a successful login.  
**Additional changes:**
- Removed unnecessary code for improved readability and maintainability.
- Updated the hover color in the navigation for better UI clarity and user experience.
---
- Implemented toast message trigger after login success.
- Refactored redundant or unused code.
- Adjusted hover color styles in the navigation bar.
---
1. Log in to the application.
2. Verify that a toast message appears indicating successful login.
3. Hover over navigation items to check updated color styling.
4. Ensure no broken functionality after code cleanup.
---
Closes #467 
Closes #484

Added toast message on successful login & SignOut in UserProfile; cleanup code; 

---

.vscode/launch.json
package-lock.json
src/components/Blog.jsx

updated the code in blog page for counting the like just once and not increasing the again and again .
Closes #[514]
-

updated the count of thumbs up in the blog page

---

src/components/BookingPage.jsx

I had fixed the issue raised in #508, i.e gender option is not visible upon clicking ... I had fixed that issue using text-gray-700; which is actually looking good...
Closes #508

Fix : Gender text color fixed

---

src/components/footer.jsx
src/utils/translationKeyMap.js

This PR redirects user to the owners social media  on clicking social media icons in footer section
closes #497

Added working social media links

---

README.md

Changes Made
🛠️ Removed repetition of sections in the README and replaced them with one complete, consolidated section for better clarity.
✨ Added a centered Tech Stack section with logos for better presentation.
📝 Created a Contributing Guidelines section in the README with clear steps for forking, branching, making changes, and submitting PRs.
🌐 Highlighted the need for Hindi translations and compressed image usage in contributions.
🔗 Added a Back to Top button at the bottom of the README (centered for better readability).
Impact
Improves readability by removing duplicate content and keeping a single, well-structured version of each section.
Enhances developer onboarding by providing clear contribution steps.
Makes navigation easier with the Back to Top button.
Improves overall …

[DOCS] Revamp README – Remove Repetition, Add Contributing Section & Back to Top Button

---

package-lock.json
src/components/hero.jsx
src/index.css

Added swap button between departure and destination input fields

 Swap Button

---

src/components/DonatePage.jsx

Closes #515 
@NishantRana07  ,  Please Review my code and merge it.

Fix : Mobile Number accepting Non numeric character in donate section

---

package-lock.json
src/components/Trip.jsx

📌 Summary
Added interactive hover effects and smooth animations to the card component for better UI experience.
🔄 Changes Made
Added hover:shadow-xl, hover:scale-[1.02], and hover:border-blue-400 for interactive hover feedback.
Implemented transition-all duration-500 ease-in-out for smooth animation.
Added hover:-translate-y-1 to give a subtle lift effect.
🎯 Motivation
Improves UI responsiveness and makes the card feel more engaging and modern.
🖼️ Screenshots / Demo
✅ Checklist
Code follows project guidelines
Hover effect tested in browser
closed #443

feat: added new UI animations

---

package-lock.json
src/components/fallbackData.jsx

added post in routes and news
Closes #536

added post in routes and news
